.github/workflows/ci.yml, .github/workflows/release.yml, .travis.yml, Ballerina.lock, Ballerina.toml, README.md, src/microsoft.onedrive/Module.md, src/microsoft.onedrive/onedrive_constants.bal, src/microsoft.onedrive/onedrive_endpoint.bal, src/microsoft.onedrive/onedrive_errors.bal, src/microsoft.onedrive/tests/main_test.bal
We have split the [Microsoft graph connector](https://github.com/ballerina-platform/module-microsoftgraph) into two separate connectors. This PR corresponds to one of the connectors which handles operations related to accessing Microsoft OneDrive.
- Split the [Microsoft graph connector](https://github.com/ballerina-platform/module-microsoftgraph) into two separate connectors
- Migrate the code to latest Ballerina release ([Swan Lake Preview1](https://ballerina.io/swan-lake/learn/))
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A …
=> Add implementation related to Microsoft OneDrive connector

README.md, src/microsoft.onedrive/Module.md
Update Ballerina version information to Ballerina Preview 3
Update Ballerina version information to Ballerina Preview 3
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
=> Update ballerina version information

README.md
>Change the size of the image in the documentation
=> Change the Documentation image size

README.md
=> Increase the documentation image size

README.md, gradle.properties, onedrive/Dependancies.toml, onedrive/Package.md, onedrive/client_endpoint.bal, onedrive/tests/test.bal
> $subject
> Updated the Dependencies.toml file and gradle.properties with SL Alpha 5 version
> Update Readme.md and Package.md files
> Insert taint check parameters necessary for the SL Alpha 5 version
=> Do necessary changes for the version bump from SL Beta 1 to SL Alpha 5

.github/workflows/ci.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml
=> [SL Alpha5] Update release action file with ballerina-action branch name

.github/workflows/release.yml
=> Change the working directory for the release

README.md
Reviewed the content and did a few changes to the document structure and content. Did a few text formatting changes too, which we can consider applying if it makes sense.
=> Apply review suggestions

README.md, onedrive/Dependencies.toml, onedrive/Package.md
- Bump version to slbeta3 in Dependencies.toml, README.md and Package.md
JDK 11
Ballerina SLBeta3-SNAPSHOT
=> Bump versions for slbeta3 in master branch 

gradle.properties, onedrive/Dependencies.toml
$title
JDK 11
Ballerina SLBeta3
=> Bump dependency versions for Ballerina SLBeta3

onedrive/client_endpoint.bal, onedrive/samples/search_drive_items.bal, onedrive/tests/test.bal
- Fix https://github.com/wso2-enterprise/choreo/issues/7924
JDK 11
Ballerina SLBeta3
=> [SLBeta3] Fix operation output streams to suit Ballerina Beta3 update

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, README.md, onedrive/Dependencies.toml
Related https://github.com/ballerina-platform/ballerina-extended-library/issues/128
One line release note: 
- Add slbeta4 migration changes
**Test Configuration**:
* Ballerina Version: Ballerina swan lake beta 4
* Operating System: Ubuntu (Linux)
* Java SDK: Java 11
=> Add slbeta4 migration changes

README.md, gradle.properties, onedrive/Ballerina.toml, onedrive/Dependencies.toml, onedrive/Package.md
- Bump version to `2.1.0`
- Update Ballerina version to `SLBeta6` in Package.md 
- Regenerate Dependencies.toml with `SLBeta6`
- Add `distribution = "slbeta6"` in Ballerina.toml
=> Prepare for 2.1.0 release with SLBeta6

onedrive/client_endpoint.bal, onedrive/stream_implementer.bal, onedrive/tests/test.bal, onedrive/utils.bal
=> Fix warnings for SLBeta6 release

.github/workflows/daily-build.yml, build.gradle, gradle.properties
- Remove unnecessary gradle steps in dailybuild
- Remove unnecessary ballerinaLangVersion in gradle.properties
=> Remove unnecessary gradle steps in dailybuild

onedrive/Dependencies.toml
- Update Dependencies.toml with latest standard library versions
=> Re-generate Dependencies.toml with latest pack

gradle.properties, onedrive/Ballerina.toml, onedrive/Dependencies.toml, onedrive/Package.md
=> Prepare for 2.2.0 release

onedrive/Ballerina.toml, onedrive/Dependencies.toml, onedrive/Package.md, onedrive/client_endpoint.bal, onedrive/config-types.bal, onedrive/stream_implementer.bal, onedrive/types.bal
* Update ConnectionConfig record
* Bump connector version and ballerina version in Ballerina.toml
* Bump ballerina version in Package.md
* Update Dependencies.toml with Ballerina 2201.2.0
* Use HTTP 1.1
* Make proxy as nillable in ClientHttp1Settings
=> Update ConnectionConfig record

onedrive/client_endpoint.bal, onedrive/config-types.bal
- Remove `clientConfig` from `OAuth2RefreshTokenGrantConfig`
=> Remove clientConfig from OAuth2RefreshTokenGrantConfig record

onedrive/config-types.bal, onedrive/stream_implementer.bal
=> Update ClientConfiguration record in stream implementation

.github/workflows/dev-stg-release.yml, .github/workflows/release.yml, onedrive/Ballerina.toml, onedrive/Package.md, onedrive/types.bal
=> Bump bal version to 2201.2.1

onedrive/client_endpoint.bal, onedrive/drive.bal, onedrive/stream_implementer.bal, onedrive/utils.bal
=> Update http version

README.md, onedrive/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/474
=> Update Slack channel occurrences with Discord

.github/workflows/release.yml
- Remove tests in the Release workflow
=> Remove test in the release workflow

onedrive/Ballerina.toml, onedrive/Dependencies.toml, onedrive/Package.md
$Subject
Fixes # https://github.com/ballerina-platform/ballerina-extended-library/issues/475
=> Update to Ballerina version 2201.3.0

.github/workflows/ci.yml, .github/workflows/daily-build.yml, .github/workflows/dev-stg-release.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, onedrive/tests/test.bal
Fix daily build. Locally tests passed. However, when run in Github workflow they failed. When investigated, I saw there are some issues in 
1. How tests are dependent on each other 
2. Variable updated by two tests are referred by other tests (two writers can make it a mess)
This PR is to fix them. 
Related issue : https://github.com/wso2-enterprise/choreo/issues/16598
=> Fix daily build by fixing test dependecies

onedrive/tests/test.bal
Wrong dependencies between tests causing issues in the daily build. Carefully analysed them and placed the correct dependencies. 
Related issue: https://github.com/wso2-enterprise/choreo/issues/16598
=> Fix dependecies between tests

ballerina/data_mappings.bal, ballerina/tests/test.bal, ballerina/types.bal
$title.
Related Pull Requests (remove if not relevant)
- Pull request 1
- Pull request 2
One line release note: 
- One line describing the feature/improvement/fix made by this PR 
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Ballerina Version:
* Operating System:
* Java SDK:
=> Fix failing test cases
